### ISSUE TITLE
Adding/removing number from input loses focus and changes keyboard

### ISSUE THREAD

**Issue by danialgoodwin** [MrBIMC/MaterialSeekBarPreference#6]
Thanks for sharing and open sourcing this widget! If I get time I'll see if I can also contribute some improvements. But, for now, as I review this, I'm going to point out some bugs for other devs and contributors to see.
- Deleting a number (or inputting a number) in input area causes focus to be lost and keyboard to change from numeric to regular text.

Tested on Moto X Android 5.1 and Nexus 4 Android 5.0, in a new project, target SDK 22.

**Comment by MrBIMC** [comment]
Woa, actually, this is a new bug that appeared in the latest release. v0.6 didn't have it!

**Comment by MrBIMC** [comment]
UPD: Found and fixed this issue(i was using setValue instead of persistInt. Both are doing the same, but setValue also force calls notifyChanges, which did something to focus). Will release new version of lib when implement stuff that was requested in another issue.

Another focus-related issue is "It required to tap on edittext twice to get focus on a field and keyboard opened in num-mode". But actually, afaik it's not a bug but intended behavior so it is solvable by adding android:windowSoftInputMode="adjustPan" into activity tag.
